#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../../autoload.php')) {
    // load autoload file when installed as a composer package
    require_once(__DIR__ . '/../../../autoload.php');
} elseif (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    // load autoload file when in development
    require_once(__DIR__ . '/../vendor/autoload.php');
}

shell_exec("php ./src/CI.php $argv[0] $argv[1] $argv[2]");
