name: "PHPCS - CI"

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  push:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"

jobs:
  phpcs:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PHP_CodeSniffer
        uses: chindit/actions-phpcs@master
        with:
          files: "**.php"
          standard: phpcs.xml
          dir: src/
