on: [push]
name: "PHPStan - CI"

jobs:
  phpstan:
    name: Run PHPStan (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.4", "8.5"]
    steps:
      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, json

      # Checkout project
      - name: Checkout project
        uses: actions/checkout@v5

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse conf src --configuration=phpstan.neon --autoload-file=src/resource/ConstantPhpStan.php --memory-limit=512M
