name: "PHPUnit - CI"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install composer and dependencies
        uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 9.5.21
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml
