name: "PHPUnit - CI"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Ajuste para a versão necessária
          extensions: xdebug
          ini-values: |
            memory_limit=512M
          coverage: xdebug

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          version: 10.5.20
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml
