name: "PHPUnit - CI"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout Code
        uses: actions/checkout@v2

      # Configurar a versão correta do PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: "8.3"
          extensions: xdebug
          ini-values: |
            memory_limit=512M
          coverage: xdebug

      # Verificar versão do PHP após setup
      - name: Validate PHP version
        run: php -v

      # Instalar dependências do Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Verificar dependências instaladas corretamente
      - name: Validate Composer dependencies
        run: composer check-platform-reqs

      # Executar PHPUnit
      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./coverage.xml
