name: "PHPUnit - CI"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: xdebug
          ini-values: |
            memory_limit=512M
          coverage: xdebug

      # Show PHP version
      - name: Show PHP version
        run: php -v

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Check Composer platform requirements
      - name: Check Composer platform requirements
        run: composer check-platform-reqs

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover ./coverage.xml
